x-team/xp-ui

.snapguidist/__snapshots__/VideoPlayer-1.snap
.snapguidist/__snapshots__/VideoPlayer-11.snap
.snapguidist/__snapshots__/VideoPlayer-13.snap
.snapguidist/__snapshots__/VideoPlayer-15.snap
.snapguidist/__snapshots__/VideoPlayer-17.snap
.snapguidist/__snapshots__/VideoPlayer-3.snap
.snapguidist/__snapshots__/VideoPlayer-5.snap
.snapguidist/__snapshots__/VideoPlayer-6.snap
.snapguidist/__snapshots__/VideoPlayer-7.snap
.snapguidist/__snapshots__/VideoPlayer-8.snap
.snapguidist/__snapshots__/VideoPlayer-9.snap
lib/auto-ui.js
src/components/VideoPlayer.js
src/components/VideoPlayer.md
src/index.js

Closes #18 
Was a fun one :-) Actually, I made it work with two types of videos:
* embedded videos, like on our `CEOMessage` page, using `embedded` boolean prop
Can be customised with `width`, `height` and whether to show controls (`showControls`)
* regular video files links, default state
Can be customised with `width`, `height`, whether to show controls (`showControls`), and a `poster` to preload in place of video
Now we can substitute all the usage of video controls in `Auto` with this component.

Introduce VideoPlayer UI component

---

.snapguidist/__snapshots__/ApplicantBadge-5.snap
.snapguidist/__snapshots__/ApplicantBadge-7.snap
.snapguidist/__snapshots__/ApplicantBadge-9.snap
lib/auto-ui.js
src/components/ApplicantBadge.js
src/components/ApplicantBadge.md

Fixes https://github.com/x-team/auto/issues/654
**Type of Release:** Fix
* Provide defaults for missing props
* Only render name row if any of first name / last name is provided
* Extend spec page with more cases to prove it works in different scenarios:
* missing `firstName`
* missing `lastName`
* missed both props
* Handle avatar's alt text properly

Handle missing name-related props

---

.snapguidist/__snapshots__/ApplicantBadge-1.snap
.snapguidist/__snapshots__/ApplicantBadge-11.snap
.snapguidist/__snapshots__/ApplicantBadge-13.snap
.snapguidist/__snapshots__/ApplicantBadge-3.snap
.snapguidist/__snapshots__/ApplicantBadge-7.snap
.snapguidist/__snapshots__/ApplicantBadge-9.snap
lib/auto-ui.js
src/components/ApplicantBadge.js
src/components/ApplicantBadge.md

Fixes #62 
- added a new `avatar` prop, so you can pass in a custom avatar element rather than using the default one generated by gravatar.
- cleaned up typography. Before:
After:

Cleanup ApplicantBadge typography, allow custom avatar

---

.snapguidist/__snapshots__/SolutionForm-1.snap
.snapguidist/__snapshots__/SolutionForm-3.snap
.snapguidist/__snapshots__/SolutionForm-5.snap
.snapguidist/__snapshots__/SolutionForm-7.snap
.snapguidist/__snapshots__/SolutionForm-9.snap
lib/auto-ui.js
src/components/SolutionForm/index.js
src/styles/theme.js

Closes #79 
Paints the texarea in red when an error attempt is passed on `SolutionForm`.
I am not very fond of the way I added styles to the textarea, my best approach would've been to add the normal text area styles and do something like `textareaStyles.compose(redborders)`, but compose is deprecated on `cmz`. Any suggestions are appreciated.

Add error state for solution form

---

.snapguidist/__snapshots__/CollapsibleSection-1.snap
.snapguidist/__snapshots__/CollapsibleSection-11.snap
.snapguidist/__snapshots__/CollapsibleSection-13.snap
.snapguidist/__snapshots__/CollapsibleSection-15.snap
.snapguidist/__snapshots__/CollapsibleSection-3.snap
.snapguidist/__snapshots__/CollapsibleSection-5.snap
.snapguidist/__snapshots__/CollapsibleSection-7.snap
.snapguidist/__snapshots__/CollapsibleSection-9.snap
lib/auto-ui.js
src/components/ui/CollapsibleSection.js
src/components/ui/CollapsibleSection.md

Requirement for https://github.com/x-team/auto/issues/870
This PR includes updates for `<CollapsibleSection />`:
- new prop `small` (boolean, default to false) that renders visually differently, with this prop set to true header is smaller and the section have no paddings;
- empty `children` is optional and will render the component instead null as before, with this change, when children is null, the component will not be clickable and the plus/minus icon will not be displayed;
Small display with content:
```js
<CollapsibleSection
title="Consectetur suscipit alias velit magni tenetur veritatis sed fuga"
visible=<p>This paragraph is always visible. Ipsa recusandae sequi, dicta laboriosam rerum ad ex voluptatibus nostrum fugiat.</p>
small
>
<p>Lorem ipsum dolor sit amet, consectetur …
```

Include new render options for CollapsibleSection

---

src/components/ui/ErrorBox.js

Fixes #118 
- more text contrast
- removed italic style
- removed left/right margin
Now looks like this:

Improve readability of ErrorBox

---

.snapguidist/__snapshots__/InputField-1.snap
.snapguidist/__snapshots__/InputField-11.snap
.snapguidist/__snapshots__/InputField-3.snap
.snapguidist/__snapshots__/InputField-5.snap
.snapguidist/__snapshots__/InputField-7.snap
.snapguidist/__snapshots__/InputField-9.snap
.snapguidist/__snapshots__/InputGroup-1.snap
.snapguidist/__snapshots__/InputGroup-3.snap
lib/auto-ui.js
src/components/forms/InputField.js

Closes: https://github.com/x-team/auto-ui/issues/123
This is causing availability fields to cut off on mobile in auto: https://github.com/x-team/auto/issues/916
Before:
After:

Make InputField labels inherit display property

---

.snapguidist/__snapshots__/InputField-11.snap
.snapguidist/__snapshots__/InputField-13.snap
.snapguidist/__snapshots__/InputField-7.snap
.snapguidist/__snapshots__/InputField-9.snap
lib/auto-ui.js
src/components/forms/InputField.js
src/components/forms/InputField.md
src/styles/theme.js

Resolves: #132
This toggle switch component is implement as variation over simple `checkbox` input.
I added definitions object for these types variation, so `sliding-checkbox` type becomes `checkbox` in the DOM, but we can style it differently and use slightly different syntax.
This was particularly useful for this component, where I wanted underlying logic to be the same as if it was a checkbox, but wanted some complicated styling.
https://cl.ly/360b3J0A2f0M/Screen%20Recording%202018-05-04%20at%2003.34%20PM.mov

Add toggle switch component

---

.snapguidist/__snapshots__/VideoPlayer-1.snap
.snapguidist/__snapshots__/VideoPlayer-11.snap
.snapguidist/__snapshots__/VideoPlayer-13.snap
.snapguidist/__snapshots__/VideoPlayer-17.snap
.snapguidist/__snapshots__/VideoPlayer-19.snap
.snapguidist/__snapshots__/VideoPlayer-21.snap
.snapguidist/__snapshots__/VideoPlayer-23.snap
.snapguidist/__snapshots__/VideoPlayer-3.snap
.snapguidist/__snapshots__/VideoPlayer-5.snap
.snapguidist/__snapshots__/VideoPlayer-7.snap
.snapguidist/__snapshots__/VideoPlayer-9.snap
lib/auto-ui.js
src/components/ui/VideoPlayer.js
src/components/ui/VideoPlayer.md

Fixes x-team/auto#1131
- Normalizes the video player props to match video tag attrs.
branch | PR
`1131-allow-playback-and-re-record-of-video` | [Auto](https://github.com/x-team/auto/pull/1223)
`1131-allow-playback-and-re-record-of-video` | [Auto API](https://github.com/x-team/auto-api/pull/400)
- Navigate to the `VideoPlayer` component section.
- Make sure the props match the `video` attrs.

Normalize video player props to match video tag attrs

---

lib/auto-ui.js
src/components/ui/ApplicantBadge.js

This PR prevents the `0` from appears as content inside ApplicantBadges:

Fix bug with empty arrays on ApplicantBadge

---

lib/auto-ui.js
src/components/ui/ApplicantBadge.js
src/components/ui/ApplicantBadge.md

This is an hotfix that affects https://github.com/x-team/auto/issues/1293.
I was trying to render my custom component inside `ApplicantBadge` and it was not working because of the missing brackets.
before:
after:

hotfix - missing function call brackets 

---

.snapguidist/__snapshots__/AttachFiles-1.snap
.snapguidist/__snapshots__/AttachFiles-3.snap
.snapguidist/__snapshots__/AttachFiles-5.snap
.snapguidist/__snapshots__/Dropdown-3.snap
.snapguidist/__snapshots__/Dropdown-7.snap
.snapguidist/__snapshots__/Note-3.snap
.snapguidist/__snapshots__/Note-5.snap
lib/auto-ui.js
src/components/ui/AttachFiles.js
src/components/ui/AttachFiles.md

Fixes x-team/auto#1372
- Updates the attach files style when in preview mode.
branch | PR
`1372-notes-bugs-—-do-not-make-initial-note-pre-save` | [Auto](https://github.com/x-team/auto/pull/1418)
- Navigate to the `AttachFiles ` component section.
- Make sure the preview mode works.

Update attach files style when in preview mode

---

.snapguidist/__snapshots__/Note-3.snap
.snapguidist/__snapshots__/Note-5.snap
.snapguidist/__snapshots__/SearchForm-1.snap
.snapguidist/__snapshots__/SearchForm-3.snap
.snapguidist/__snapshots__/SearchForm-5.snap
lib/auto-ui.js
src/components/ui/SearchForm.js

**Release Type:** *Breaking change*
Fixes https://x-team-internal.atlassian.net/browse/XP-2239
These changes remove the show button from the search form and rename the `Filter` button text by `Show`.
List related PRs against other Auto repos if applicable:
Branch | PR
XP-2239-remove-show-button-and-rename-filter-button | [Auto](https://github.com/x-team/auto/pull/1531)
1. Go to the Search applicants/list screen. 
2. The show button next to the lists select should be removed.
3. The text of the `Filter` button should be changed to `Show`.
4. The search form works as expected.
List Screen and Search Form.

Remove show button and rename filter button

---

.snapguidist/__snapshots__/SearchForm-1.snap
.snapguidist/__snapshots__/SearchForm-3.snap
.snapguidist/__snapshots__/SearchForm-5.snap
lib/auto-ui.js
src/components/ui/SearchForm.js

**Release Type:** *Bug fix*
Fixes https://x-team-internal.atlassian.net/browse/XP-2290
Updated fields order accordingly expected. The view display switcher remained on same place because as per discussion with Paul it's part of the scope of https://x-team-internal.atlassian.net/browse/XP-2284
SearchForm in tabular view.
| View mode | Before | After |
| - | - | - |
| Tabular | <img width="1680" alt="screen shot 2018-09-27 at 2 15 52 pm" src="https://user-images.githubusercontent.com/131859/46163509-c2c35e80-c261-11e8-92b2-b0ad264af07c.png"> | <img width="1680" alt="screen shot 2018-09-27 at 2 26 18 pm" src="https://user-images.githubusercontent.com/131859/46163525-ca830300-c261-11e8-9094-6da5cbfb00b2.png"> |
| List | <img width="866" alt="screen shot 2018-09-27 at 2 39 28 pm" …

Update fields order in SearchForm

---

.snapguidist/__snapshots__/Keywords-1.snap
.snapguidist/__snapshots__/Keywords-3.snap
.snapguidist/__snapshots__/SearchForm-1.snap
.snapguidist/__snapshots__/SearchForm-3.snap
.snapguidist/__snapshots__/SearchForm-5.snap
lib/auto-ui.js
src/components/ui/AdminScreen.js

**Release Type:** *[Bug fix]* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2291
This small fix adjusts the `z-index` in `components/ui/AdminScreen.js:20` this is the container of the `Dropdown` that was showing this issue.
z-index is set to `10000` because it has to be higher than: 
- `components/ui/ListsScreen.js:69`
- `components/ui/SelectBox.js:23`
- Go to admin site and adjust the screen size so that the hamburger menu is above the search filters:
- Select "View in Tabular Mode" and do likewise:
Before :-1: :
After :tada: :tada:  :

Fix AdminScreen z-index

---

.snapguidist/__snapshots__/ColorPalette-1.snap
.snapguidist/__snapshots__/Keywords-1.snap
.snapguidist/__snapshots__/Keywords-3.snap
.snapguidist/__snapshots__/SearchForm-1.snap
.snapguidist/__snapshots__/SearchForm-3.snap
.snapguidist/__snapshots__/SearchForm-5.snap
.snapguidist/__snapshots__/SettingsScreen-0.snap
.snapguidist/__snapshots__/SettingsScreen-1.snap
.snapguidist/__snapshots__/SettingsScreen-3.snap
.snapguidist/__snapshots__/SettingsScreen-5.snap
lib/auto-ui.js
src/components/ui/ListsScreen.js
src/components/ui/SettingsScreen.js
src/components/ui/SettingsScreen.md
src/index.js
src/styles/theme.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2232
This PR includes a new SettingsScreen component.
branch | PR
`XP-2357-create-settings-route` | [Auto](https://github.com/x-team/auto/pull/1579)
The demonstration in Styleguidist of this kind of component is usually quite broken, because have some pros that relates to window screen. The preview bellow is the final implementation in the app, along with PR https://github.com/x-team/auto/pull/1579:

Include SettingsScreen

---

.snapguidist/__snapshots__/InputField-11.snap
.snapguidist/__snapshots__/InputField-13.snap
.snapguidist/__snapshots__/InputField-17.snap
.snapguidist/__snapshots__/InputField-5.snap
.snapguidist/__snapshots__/InputField-7.snap
.snapguidist/__snapshots__/ListsEditor-1.snap
.snapguidist/__snapshots__/Modal-5.snap
.snapguidist/__snapshots__/SearchForm-1.snap
.snapguidist/__snapshots__/SearchForm-3.snap
.snapguidist/__snapshots__/SearchForm-5.snap
.snapguidist/__snapshots__/SelectBox-13.snap
.snapguidist/__snapshots__/SelectBox-7.snap
.snapguidist/__snapshots__/SelectBox-9.snap
lib/auto-ui.js
src/components/forms/InputField.js

**Release Type:** *Bug fix* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2374
Just a quick fix to make sure input fields with post text is displayed inline.
The bug can be seen fixed at http://localhost:8000/applicant/57d1ccdab391a4829ff628fbbc52a82f/info

 Fix layout bug on InputField

---

package-lock.json
package.json

Creating this just so that we don't forget.
Details of the resolved issue here:
https://github.com/joshwnj/babel-plugin-cmz-names/pull/1
Already tested successfully in my Windows environment with this repo.

Update `babel-plugin-cmz-names` to fix Windows issue

---

.snapguidist/__snapshots__/Keywords-1.snap
.snapguidist/__snapshots__/Keywords-3.snap
.snapguidist/__snapshots__/Note-3.snap
.snapguidist/__snapshots__/Note-5.snap
.snapguidist/__snapshots__/Note-9.snap
.snapguidist/__snapshots__/SearchForm-1.snap
.snapguidist/__snapshots__/SearchForm-3.snap
.snapguidist/__snapshots__/SearchForm-5.snap
lib/auto-ui.js
src/components/ui/Keywords.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2181
Include ability to persist keyword from input of Keywords on blur
1. While typing new string into keywords field, without keypressing tab or enter, leave the field or click on `show` button, the new string should be added as a keyword tag and in case of `show` button is pressed the search with the new keyword should be performed.
`Keywords` component.

Include ability to persist keyword from input of Keywords on blur

---

package.json
webpack.standalone.js

**Release Type:** *Dev Improvements*
While working and investigating https://github.com/x-team/auto-ui/pull/270, it was getting difficult to nail down the root cause of the bug because it was related to an integration between an `auto` screen and an `auto-ui` component.
I decided to add source maps so that it was possible to debug `auto-ui` code from the running application in `auto`. 
I also added a `watch` npm script to streamline the development flow even more. Using `npm link`, the source maps and watch mode, doing a change in `auto-ui` becomes immediately available and debuggable in `auto` (after compilation finishes, of course).
I think this will bring a boost to our productivity moving forward! 
Hope you guys feel the same way.
**Please review the necessary changes in Auto for this …

Add source maps to built lib

---

src/components/ui/Note.js
src/components/ui/RichTextEditor.js
src/components/ui/RichTextEditor.stories.js
src/index.js

**Release Type:** *Non breaking feature*
Fixes https://x-team-internal.atlassian.net/browse/XP-2673
- Implement RichTextEditor component in Note component 
- Add `disabled` prop to `RichTextEditor`
branch | PR
XP-2673-rich-text-editor-in-notes | [Auto](https://github.com/x-team/auto/pull/1761)
See https://github.com/x-team/auto/pull/1761
- `Note` component (used when editing notes from the applicant's profile)
See https://github.com/x-team/auto/pull/1761

 Implement RichTextEditor component in Note component 

---

src/components/ui/ListsEditor.js
src/components/ui/SelectBox.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2412
Removed local state for dismissed item states in favor of API handling.
branch | PR
`XP-2412-fix-dismissed-delete-messages-at-edit-lists` | [Auto](https://github.com/x-team/auto/pull/1760)
This is better reproducible in app, see related `auto` PR https://github.com/x-team/auto/pull/1760.
SelectBox and ListsEditor
No visual updates. The components remain with same states but the behaviour got some fixes, and it can be experienced integrated in app, see related PR https://github.com/x-team/auto/pull/1760.

Fix SelectBox's dissmissing messages behaviour

---

src/components/ui/RichTextEditor.js
src/components/ui/RichTextEditor.stories.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2705
1- Removed all of these buttons from the default editor config
* Task
* Indents [left & right]
* Table
* Image
* CodeBlock
2- Added feature to configure with a different set of buttons in the `RichTextEditor.js` component.
1- Go to `RichTextEditor` component on storybook
2- Confirm that the toolbar buttons listed in the description are not there.
- RichTextEditor

Add default toolbar items

---

src/components/ui/SelectBox.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2721
> Set up a `max-width` for `SelectBox` items and have different words length without horizontal scroll.
branch | PR
XP-2721-fix-dropdown-width| [Auto](https://github.com/x-team/auto/pull/1779)
- SelectBox component

Fix SelectBox width of items elements

---

src/components/ui/Note.js
src/components/ui/RichTextEditor.js
src/components/ui/RichTextEditor.stories.js
src/utils/helpers.js

**Release Type:** *Breaking Changes*
Fixes https://x-team-internal.atlassian.net/browse/XP-2716
Add a `more` prop to the `RichTextEditor` component that will add support for the `viewer` mode.
1. Open the new `viewer` story under the `RichTextEditor` component
- `RichTextEditor` component
- `Note` component (rendering)
`RichTextEditor` component in `viewer` mode.
There are slight differences in how our old markdown engine rendered content versus how Toast UI does it:
**before (with `markdown-to-jsx`)**
**after (with Toast UI)**

Use Toast UI Editor Viewer component for Notes

---

src/components/ui/RichTextEditor.js
src/components/ui/RichTextEditor.stories.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2780
This PR includes ability to hide the toolbars of RichTextEditor via pro `hideToolbar`.
branch | PR
`XP-2780-add-new-profile-summary` | [Auto](https://github.com/x-team/auto/pull/1796)
1. Grab the latest from this branch
2. Run `npm start`
3. Go to http://localhost:9001/?selectedKind=UI%20Components%2FRichTextEditor&selectedStory=with%20hidden%20toolbar
4. Observe that the toolbar is not visible anymore
`RichTextEditor`

Include hideToolbar prop in the RichTextEditor

---

src/components/ui/GenericTabs/Container.js
src/components/ui/GenericTabs/GenericTabs.stories.js

**Release Type:** *Bug fix* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2846
I spot the bug while I was trying to implement the Context filers with list/all tabs. The issue was that the pane was not updated while rest the page was. The issue was that it was cached in construction phase.
1. Go into storybook
1. Go into `GenericTabs/Debug` section
1. And cliick on the `Increment` button
1. You should see the value incremented in both places
All GenericTab instances
**Before fix**
Only Tab.Header value is changing.
**After fix**
Both values are changing.

Generic tabs fix

---

src/components/ui/Filters/Filter.js
src/components/ui/Filters/Filters.stories.js

**Release Type:** *Dev Improvements* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2854
Remove isCollapsible behaviour entirely from Filters.Filter component
branch | PR
`XP-2854-remove-expand-collapse-from-filter-inputs` | [Auto](https://github.com/x-team/auto/pull/1827)
1. run `npm start`
1. go to http://localhost:9001/?selectedKind=UI%20Components%2FFilters%2FDebug&selectedStory=standalone%20Filter
1. observe that the `isCollapsible` prop is no longer available
- `Filters/Filters.stories.js`

Remove isCollapsible behaviour entirely from Filters.Filter component

---

src/components/ui/ColumnsCustomizer.js
src/components/ui/ColumnsCustomizer.stories.js
src/components/ui/MetaGroup.js
src/components/ui/MetaGroup.stories.js
src/components/ui/ResultCount.js
src/components/ui/SelectBox.js
src/index.js

**Release Type:** *non breaking changes* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2800
Created a new UI component based on the already existing SelectBox/Dropdown component, styled to be used above the DataGrid. This component is used to choose what columns of the DataGrid need to be displayed.
In the Storybook search field type ColumnsCustomizer, you will see the option to visualize the created new UI, click on the sub menu "basic usage", you will se the UI component being shown on the viewport.
- `ColumnsCustomizer.js`
- `ColumnsCustomizer.stories.js`

Create new UI to select the columns of the datagrid and be displayed above the datagrid

---

src/components/ui/SearchForm.js
src/components/ui/SelectBox.js

**Release Type:** *Bug fix*
Fixes https://x-team-internal.atlassian.net/browse/XP-2940
Fix SelectBox visible items height calculation.
branch | PR
`XP-2940-fix-selectbox-visibleitems-prop` | [XP](https://github.com/x-team/xp/pull/1850)
- `visitbleItems` value should works as expected both for normal size as for small.
`SelectBox`
This PR fixed a regression, so many places now behaves as expected:

Fix SelectBox visibleItems height calculation

---

src/components/ui/ActivityLog.js
src/components/ui/ActivityLog.stories.js
src/components/ui/ActivityLogsDisplay.stories.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2782
Not sure why, but we had an unused data `details` that given existing codebase it should be `info`. I fixed that and updated the showcases.
branch | PR
`XP-2782-track-and-display-exclusion-reason-in-activity-log` | [XP](https://github.com/x-team/xp/pull/1864)
`XP-2782-track-and-display-exclusion-reason-in-activity-log` | [XP API](https://github.com/x-team/xp-api/pull/645)
1. Run `npm start`
1. Go to http://localhost:9001/?selectedKind=UI%20Components%2FActivityLogsDisplay
1. Observe that some grouped items might have activities with extra info included (it's random generated data)
1. Go to http://localhost:9001/?selectedKind=UI%20Components%2FActivityLogsDisplay%2FActivityLog …

Track and display exclusion reason in activity log

---

src/components/hocs/withAutosize.js
src/components/ui/Button.js

**Release Type:** *Bug fix*
Fixes https://x-team-internal.atlassian.net/browse/XP-2991
Included default `rows` for InputField of textarea type. Fixed the padding for Button of `selectbox` type.
branch | PR
`XP-2991-create-import-profiles-screen` | [XP](https://github.com/x-team/xp/pull/1874)

Update withAutosize and Button

---

src/components/hocs/withAutosize.js
src/components/ui/Button.js
src/components/ui/ErrorBox.js
src/components/ui/SettingsImportScreen.js
src/components/ui/SettingsImportScreen.stories.js
src/components/ui/SettingsScreen.js
src/index.js

Fixes https://x-team-internal.atlassian.net/browse/XP-2955
Includes the work done at the PRs:
- https://github.com/x-team/xp-ui/pull/387
- https://github.com/x-team/xp-ui/pull/386
branch | PR
`XP-2955-import-profiles-to-list` | [XP](https://github.com/x-team/xp/pull/1876)
`XP-2955-import-profiles-to-list` | [XP API](https://github.com/x-team/xp-api/pull/649)
_Please refer to the related PRs for further instructions:_
- https://github.com/x-team/xp-ui/pull/387
- https://github.com/x-team/xp-ui/pull/386

Import profiles to list

---

.jest/setupTests.js
package-lock.json
package.json
src/__snapshots__/storyshots.test.js.snap
src/components/ui/Text.js
src/components/ui/Text.stories.js
src/components/ui/Typography.js
src/styles/theme.js
src/styles/typo.js

**Release Type:** *non-braking changes*
Fixes https://x-team-internal.atlassian.net/browse/XP-3086
Adapt `Text` to render Markdown content and apply basic typography styles.
branch | PR
`XP-3086-render-typography-with-text-on-strapisection-component` | [XP REG](https://github.com/x-team/xp-registration/pull/53)
1. Make sure to run `npm install` first
1. Run `npm start`
1. Go to http://localhost:9001/?selectedKind=UI%20Components%2FText%2FDemos&selectedStory=content%20with%20Markdown
1. Observe that the Markdown is rendered and styled as expected
1. Copy xp-ui lib files to xp node modules (e.g. in `xp` directory run `cp -R ../xp-ui/lib/ node_modules/xp-ui/lib/ && npm run watch`)
1. Navigate in the app and observe that Text usages didn't have any regression
1. Compare …

Include isMarkdown feature in Text component

---

src/__snapshots__/storyshots.test.js.snap
src/components/ui/ProfileHeaderLinks.js
src/components/ui/SvgIcon.js
src/components/ui/SvgIcon.stories.js
src/components/ui/TwoColumnsLayout.js
src/components/ui/TwoColumnsLayout.stories.js

**Release Type:** *Non-breaking changes* 
Fixes https://x-team-internal.atlassian.net/browse/XP-3122
- This PR updates `TwoColumnsLayout` component to be compatible with current needs.
- The `ProfileHeaderLinks` got an alternative style presentation (this can be removed together with Lists screen removal).
- The `SvgIcon` got a small refactor to expose available icons, that's used on TwoColumnsLayout story, where you can live-preview all existing icons of the collection in the sidebar heading.
branch | PR
`XP-3122-display-grid-or-profile-via-the-search-ui-based-on-applicantid-query-param` | [XP](https://github.com/x-team/xp/pull/1918)
- Run `npm start`
- Go to http://localhost:9001/?selectedKind=UI%20Components%2FTwoColumnsLayout%2FDebug&selectedStory=composed%20in%20AdminS …

Update ProfileHeaderLinks, SvgIcon and TwoColumnsLayout

---

src/__snapshots__/storyshots.test.js.snap
src/components/ui/GenericCollapsible/Body.js
src/components/ui/GenericCollapsible/Container.js

Fixes https://x-team-internal.atlassian.net/browse/XP-3142
This PR changes the way GenericCollapsible hides the body, instead removing from DOM it just hides using CSS. With that the body state are persisted during visibility toggles and it becomes more performant since it doesn't cause the body to re-render every time it's expanded.
Please check **Screenshots** section below.
- GenericCollapsible
- Go to GenericCollapsible or Filters (which uses GenericCollapsible) and observe the DOM. The rendered element are always there and it just update the CSS classes to hide the body.
- Observe that the expand/collapse experience is improved:
- The exact state of the panel body is preserved (e.g. when scrolling the body of a panel, even after collapsing and …

Improve GenericCollapsible to become more performant and prevent unnecessary re-render of the body content

---

src/__snapshots__/storyshots.test.js.snap
src/components/ui/Filters/ExtraButton.js
src/components/ui/Filters/Filters.stories.js
src/components/ui/Filters/Heading.js
src/components/ui/Filters/index.js

Fixes https://x-team-internal.atlassian.net/browse/XP-3098
Add extra prop in the Filter.Heading and include new Filter.ExtraButton component.
branch | PR
`XP-3098-add-reset-button-for-filters` | [XP](https://github.com/x-team/xp/pull/1935)
Please refer to the screenshot below.
Filters components.

Add extra prop in the Filter.Heading

---

src/__snapshots__/storyshots.test.js.snap
src/components/ui/ApplicantGrid.js
src/components/ui/Filters/Container.js
src/components/ui/Filters/Filters.stories.js
src/components/ui/Filters/Group.js

Fixes https://x-team-internal.atlassian.net/browse/XP-3183
Include onKeyPress on Filters.Container component
branch | PR
`XP-3183-show-results-after-completing-updates-to-search-filters-on-profile-display` | [XP](https://github.com/x-team/xp/pull/1960)
- While on an input field inside the Filters component, the keyPress will be listening and trigger the provided action
- `Filters.Container`

Include onkeypress on Filters.Container component

---

package-lock.json
src/__snapshots__/storyshots.test.js.snap
src/components/ui/Dropdown.js
src/components/ui/MetaGroup.js
src/components/ui/ResultCount.js

Fixes https://x-team-internal.atlassian.net/browse/XP-3165
Added the `data-testid` attribute in some views layout of the ResultCount, MetaGroup, and Dropdown
https://github.com/x-team/xp/pull/1949
branch | PR
XP-3165-e2e-urlParams-localstorage | [XP](https://github.com/x-team/xp/pull/1949)
- ResultCount
- MetaGroup
- Dropdown

Add required data-testid attributes to be able to add the E2E tests for the SearchScreen URL and LS

---

src/__snapshots__/storyshots.test.js.snap
src/components/ui/DataGrid.js
src/components/ui/SearchResult.js

**Release Type:** *Non-breaking change*
Fixes https://x-team-internal.atlassian.net/browse/XP-3014
Make the rows count dynamically related to the amount of records available.
- Load lists with different amount of records to observe how the DataGrid behaves
- It should not have empty scrollable space on any case
SearchResults and DataGrid

Fix DataGrid vertical scrolling

---

src/__snapshots__/storyshots.test.js.snap
src/components/forms/SolutionForm/index.js
src/components/ui/ApplicantBadge.js
src/components/ui/ApplicantGrid.js
src/components/ui/Button.js
src/components/ui/DataGrid.js
src/components/ui/Dropdown.js
src/components/ui/Filters/Filter.js
src/components/ui/Filters/Group.js
src/components/ui/Filters/Heading.js
src/components/ui/Filters/Label.js
src/components/ui/Filters/TabButton.js
src/components/ui/HeadingWithQuickSearch.js
src/components/ui/ListExclusionFormPopup.js
src/components/ui/ListsEditor.js
src/components/ui/MetaGroup.js
src/components/ui/QuickSearchButton.js
src/components/ui/RoadmapLevel.js

Fixes https://x-team-internal.atlassian.net/browse/XP-3170
- Added the `data-testid` attribute in the view of some components to be able to add the E2E required by the A/C
- https://github.com/x-team/xp-ui/pull/423 (CLOSED). The PR#423 was closed due to the high number of changes required to restore back the code style in this comment https://github.com/x-team/xp-ui/pull/423#issuecomment-520496017. This current PR has the same changes as the PR#423 but respecting the code style of the project
branch | PR
XP-3170-e2e-switching-lists | [XP](https://github.com/x-team/xp/pull/1965)
XP-3171-switching-accepted-excluded | [XP](https://github.com/x-team/xp/pull/1966)
XP-3172-performing-filtering | …

Add data-testid attribute needed for the E2E tests in the Search Page for the switching lists cases

---

src/components/styleguides/ColorPalette.js

**Release Type:** *Dev improvements*
Fixes https://github.com/x-team/xp/issues/1994
Expose HEX value at ColorPalette to help identify very similar shades.
1. Go to http://localhost:9001/?path=/story/styleguides--colorpalette
1. Observe that the HEX values are now exposed above the color blocks
- `ColorPalette`

Expose HEX value at ColorPalette
