- lib/auto-ui.js
- src/utils/elem.js
Hey @joshwnj, I'm upgrading react to v16 in `x-team/auto` and this is currently a blocker
> React.DOM -> react-dom package

- .snapguidist/__snapshots__/CollapsibleSection-11.snap
- .snapguidist/__snapshots__/Milestones-11.snap
- .snapguidist/__snapshots__/RoadmapLevel-7.snap
- lib/auto-ui.js
- package-lock.json
- package.json
> Upgrade dependencies

- .snapguidist/__snapshots__/Button-1.snap
- .snapguidist/__snapshots__/Button-11.snap
- .snapguidist/__snapshots__/Button-13.snap
- .snapguidist/__snapshots__/Button-15.snap
- .snapguidist/__snapshots__/Button-17.snap
- .snapguidist/__snapshots__/Button-19.snap
- .snapguidist/__snapshots__/Button-21.snap
- .snapguidist/__snapshots__/Button-23.snap
- .snapguidist/__snapshots__/Button-25.snap
- .snapguidist/__snapshots__/Button-27.snap
- .snapguidist/__snapshots__/Button-29.snap
- .snapguidist/__snapshots__/Button-3.snap
- .snapguidist/__snapshots__/Button-5.snap
- .snapguidist/__snapshots__/Button-7.snap
- .snapguidist/__snapshots__/Button-9.snap
- lib/auto-ui.js
- package-lock.json
- package.json
- src/components/Button.js
- src/components/Button.md
- src/components/CollapsibleSection.md
- src/components/Milestones.md
- src/components/RoadmapLevel.md
- src/components/SvgIcon.md
- src/index.js
- src/styles/theme.js
- src/styles/typo.js
Closes #14 
Took a bit longer than planned initially, but mainly because I had to revise button styles and proposed props, and mainly re-structure it in a way that allows their combined usage, by applying new styles on top of base ones. As a result, we have a highly customisable component that allows to build it whatever we wish by combining various props :)
> Add Button component

- .snapguidist/__snapshots__/RoadmapLevel-1.snap
- .snapguidist/__snapshots__/RoadmapLevel-3.snap
- .snapguidist/__snapshots__/RoadmapLevel-5.snap
- lib/auto-ui.js
- src/components/RoadmapLevel.js
- src/components/RoadmapLevel.md
Closes #8 
Also, adjust spec page along the way + small extra refactors.
> Update component to use Button UI component

- .snapguidist/__snapshots__/CollapsibleSection-1.snap
- .snapguidist/__snapshots__/CollapsibleSection-3.snap
- .snapguidist/__snapshots__/CollapsibleSection-5.snap
- .snapguidist/__snapshots__/CollapsibleSection-7.snap
- .snapguidist/__snapshots__/CollapsibleSection-9.snap
- .snapguidist/__snapshots__/RoadmapHero-1.snap
- .snapguidist/__snapshots__/Text-15.snap
- .snapguidist/__snapshots__/Text-17.snap
- .snapguidist/__snapshots__/Text-3.snap
- .snapguidist/__snapshots__/Text-5.snap
- lib/auto-ui.js
- src/components/RoadmapHero.js
Closes #43 
* make use of flexbox
* code cleanup
> Make use of flexbox and code cleanup

- .snapguidist/__snapshots__/RoadmapLevel-5.snap
- .snapguidist/__snapshots__/RoadmapTimelineElement-0.snap
- .snapguidist/__snapshots__/RoadmapTimelineElement-1.snap
- .snapguidist/__snapshots__/RoadmapTimelineElement-3.snap
- .snapguidist/__snapshots__/RoadmapTimelineElement-5.snap
- .snapguidist/__snapshots__/SvgIcon-7.snap
- lib/auto-ui.js
- src/components/RoadmapTimelineElement.js
- src/components/RoadmapTimelineElement.md
- src/index.js
- - [x] - pending
- - [x] - done
- - [x] - pending
- - [x] - done 
Fixes #10
> 10 - Create RoadmapTimelineElement

- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- src/components/ApplicantBadge.js
- src/components/ApplicantBadge.md
Fixes #51 
I also changed the layout from `inline-block` to `flex`, as we'll have much more control over the way things wrap.
> Allow passing in children to ApplicantBadge

- .travis.yml
- CNAME
> Add automated deployment of Github Pages

- .snapguidist/__snapshots__/Milestones-1.snap
- .snapguidist/__snapshots__/Milestones-3.snap
- .snapguidist/__snapshots__/Milestones-5.snap
- .snapguidist/__snapshots__/Milestones-7.snap
- .snapguidist/__snapshots__/Milestones-9.snap
- lib/auto-ui.js
- src/components/Milestones.js
Closes #57 
I assume this tiny change should be sufficient for what we look for.
> Allow changing milestone with a prop only

- lib/auto-ui.js
- src/components/HeaderBar.js
Related to: https://github.com/x-team/auto/pull/698
Before:
After:
> Fix <HeaderBar /> shadow

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-11.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- lib/auto-ui.js
- src/components/ApplicantBadge.js
- src/components/ApplicantBadge.md
This complements https://github.com/x-team/auto/pull/697 by making `ApplicantBadge` more flexible
* Add active state to highlight the whole text content area
* Remove the padding from the lefthand side
* Give a top and right padding to the text content
Should be merged first, before the https://github.com/x-team/auto/pull/697 PR.
> Tweak ApplicantBadge component

- lib/auto-ui.js
- src/components/Footer/Footer.js
- src/components/Footer/FooterBrands.js
https://github.com/x-team/auto/issues/672
> Tweak footer, fix for situation when more then 4 brands, alignment fix

- .snapguidist/__snapshots__/Footer-1.snap
- lib/auto-ui.js
- src/components/Footer/Footer.js
Closes https://github.com/x-team/auto-ui/issues/64
> 64 footer component lacks some spacing

- lib/auto-ui.js
- src/index.js
Closes #69 
Adds `SolutionForm` for exporting.
> Added missing export

- .snapguidist/__snapshots__/SolutionForm-1.snap
- .snapguidist/__snapshots__/SolutionForm-5.snap
- .snapguidist/__snapshots__/SolutionForm-7.snap
- .snapguidist/__snapshots__/SolutionForm-9.snap
- lib/auto-ui.js
- src/components/SolutionForm/index.js
- src/components/SolutionForm/index.md
Closes #74 
Adds function being passed as props to `SolutionForm` component.
> Modified Solution form in order to accept submit function as props.

- .snapguidist/__snapshots__/InputField-1.snap
- .snapguidist/__snapshots__/InputField-3.snap
- .snapguidist/__snapshots__/InputField-5.snap
- .snapguidist/__snapshots__/InputField-7.snap
- .snapguidist/__snapshots__/InputField-9.snap
- .snapguidist/__snapshots__/InputGroup-1.snap
- .snapguidist/__snapshots__/InputGroup-3.snap
- .snapguidist/__snapshots__/Roadmap-1.snap
- .snapguidist/__snapshots__/RoadmapHero-1.snap
- .snapguidist/__snapshots__/RoadmapHero-3.snap
- .snapguidist/__snapshots__/RoadmapLevel-1.snap
- .snapguidist/__snapshots__/RoadmapLevel-3.snap
- lib/auto-ui.js
- src/components/forms/InputField.js
- src/components/forms/InputField.md
- src/components/forms/InputGroup.js
- src/components/forms/InputGroup.md
- src/index.js
> Extract form related components from auto

- .snapguidist/__snapshots__/RoadmapLevel-5.snap
- .snapguidist/__snapshots__/Text-1.snap
- .snapguidist/__snapshots__/Text-11.snap
- .snapguidist/__snapshots__/Text-13.snap
- .snapguidist/__snapshots__/Text-15.snap
- .snapguidist/__snapshots__/Text-17.snap
- .snapguidist/__snapshots__/Text-19.snap
- .snapguidist/__snapshots__/Text-21.snap
- .snapguidist/__snapshots__/Text-23.snap
- .snapguidist/__snapshots__/Text-25.snap
- .snapguidist/__snapshots__/Text-27.snap
- .snapguidist/__snapshots__/Text-3.snap
- .snapguidist/__snapshots__/Text-5.snap
- .snapguidist/__snapshots__/Text-7.snap
- .snapguidist/__snapshots__/Text-9.snap
- src/components/ui/Text.js
- src/components/ui/Text.md
Closes #89
* Added a new `isPureContent` boolean prop
> Extend Text component with a new render option

- .snapguidist/__snapshots__/ApplicantScreen-1.snap
- .snapguidist/__snapshots__/ApplicantScreen-3.snap
- .snapguidist/__snapshots__/SolutionForm-1.snap
- .snapguidist/__snapshots__/SolutionForm-3.snap
- .snapguidist/__snapshots__/SolutionForm-5.snap
- .snapguidist/__snapshots__/SolutionForm-7.snap
- .snapguidist/__snapshots__/SolutionForm-9.snap
- lib/auto-ui.js
- src/components/forms/SolutionForm/Title.js
- src/components/forms/SolutionForm/index.js
- src/components/ui/ApplicantScreen.js
> Adjust UI components styles

- lib/auto-ui.js
- src/components/ui/MilestonesScreen.js
> Change 'show off' form screen paddings

- .snapguidist/__snapshots__/RoadmapHero-1.snap
- .snapguidist/__snapshots__/RoadmapHero-3.snap
- lib/auto-ui.js
- src/components/ui/RoadmapHero.js
> Change content alignment on mobile

- .snapguidist/__snapshots__/Roadmap-1.snap
- .snapguidist/__snapshots__/RoadmapTimelineElement-1.snap
- .snapguidist/__snapshots__/RoadmapTimelineElement-3.snap
- lib/auto-ui.js
- src/components/ui/Roadmap.js
- src/components/ui/RoadmapTimelineElement.js
- src/utils/helpers.js
https://github.com/x-team/auto/issues/818
Fixing scroll logic and preventing blinking
> Scroll back up on Roadmap causes blinking step icon

- .snapguidist/__snapshots__/Footer-1.snap
- lib/auto-ui.js
- src/components/ui/Footer/Footer.js
Fixes #104, fixes https://github.com/x-team/auto/issues/831
> Wipe out footer links on medium resolution and below

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-11.snap
- .snapguidist/__snapshots__/ApplicantBadge-13.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
Fixes #107 
**Release Type:** _Fix_
> Applicant's avatar is flickering bug

- .snapguidist/__snapshots__/ErrorBox-0.snap
- .snapguidist/__snapshots__/InputField-1.snap
- .snapguidist/__snapshots__/InputField-11.snap
- .snapguidist/__snapshots__/InputField-3.snap
- .snapguidist/__snapshots__/InputField-5.snap
- .snapguidist/__snapshots__/InputField-7.snap
- .snapguidist/__snapshots__/InputField-9.snap
- .snapguidist/__snapshots__/InputGroup-1.snap
- .snapguidist/__snapshots__/InputGroup-3.snap
- lib/auto-ui.js
- src/components/forms/InputField.js
- src/components/forms/InputField.md
> added-checkbox-style

- .snapguidist/__snapshots__/ErrorBox-5.snap
- .snapguidist/__snapshots__/ErrorBox-7.snap
- .snapguidist/__snapshots__/ErrorBox-9.snap
- lib/auto-ui.js
- src/components/ui/ErrorBox.js
- src/components/ui/ErrorBox.md
> Tweak ErrorBox

- .snapguidist/__snapshots__/FilterBar-0.snap
- .snapguidist/__snapshots__/FilterBar-1.snap
- .snapguidist/__snapshots__/FilterBar-2.snap
- .snapguidist/__snapshots__/FilterBar-3.snap
- .snapguidist/__snapshots__/FilterBar-5.snap
- lib/auto-ui.js
- src/components/ui/FilterBar.js
- src/components/ui/FilterBar.md
- src/index.js
> Include FilterBar component

- .snapguidist/__snapshots__/SolutionForm-1.snap
- .snapguidist/__snapshots__/SolutionForm-3.snap
- .snapguidist/__snapshots__/SolutionForm-5.snap
- .snapguidist/__snapshots__/SolutionForm-9.snap
- lib/auto-ui.js
- src/components/forms/SolutionForm/index.js
**Release type:** *Bug fix*
Fixes #121
> Misleading taken attempts counter

- .snapguidist/__snapshots__/AttachFiles-1.snap
- .snapguidist/__snapshots__/AttachFiles-3.snap
- src/components/ui/AttachFiles.js
Fixes #125 
add an id prop and return it on the onCancel and onDelete callbacks
> add id prop to AttachFile Component

- .snapguidist/__snapshots__/Avatar-1.snap
- .snapguidist/__snapshots__/Avatar-3.snap
- .snapguidist/__snapshots__/Avatar-5.snap
- .snapguidist/__snapshots__/Avatar-7.snap
- .snapguidist/__snapshots__/Avatar-9.snap
- lib/auto-ui.js
- src/components/ui/Avatar.js
- src/components/ui/Avatar.md
- src/index.js
PR for issue x-team/auto-ui#137
> Add avatar component

- .snapguidist/__snapshots__/Note-1.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/TextareaEditor-1.snap
- .snapguidist/__snapshots__/TextareaEditor-3.snap
- .snapguidist/__snapshots__/TextareaEditor-5.snap
- .snapguidist/__snapshots__/TextareaEditor-7.snap
- .snapguidist/__snapshots__/TextareaEditor-9.snap
- lib/auto-ui.js
- package-lock.json
- src/components/ui/TextareaEditor/MediumEditorWrapper.js
- src/components/ui/TextareaEditor/TextareaEditor.js
- src/components/ui/TextareaEditor/TextareaEditor.md
> Include read only mode on TextareaEditor

- .snapguidist/__snapshots__/TextareaEditor-1.snap
- .snapguidist/__snapshots__/TextareaEditor-3.snap
- .snapguidist/__snapshots__/TextareaEditor-5.snap
- .snapguidist/__snapshots__/TextareaEditor-7.snap
- .snapguidist/__snapshots__/TextareaEditor-9.snap
- lib/auto-ui.js
- src/components/ui/TextareaEditor/TextareaEditor.js
- src/components/ui/TextareaEditor/TextareaEditor.md
This PR adds large prop to `TextEditorArea` to facilitate height change but also includes default height
> Extend TextareaEditor with a size option

- .snapguidist/__snapshots__/TruncatedList-1.snap
- .snapguidist/__snapshots__/TruncatedList-11.snap
- .snapguidist/__snapshots__/TruncatedList-13.snap
- .snapguidist/__snapshots__/TruncatedList-15.snap
- .snapguidist/__snapshots__/TruncatedList-16.snap
- .snapguidist/__snapshots__/TruncatedList-17.snap
- .snapguidist/__snapshots__/TruncatedList-3.snap
- .snapguidist/__snapshots__/TruncatedList-5.snap
- .snapguidist/__snapshots__/TruncatedList-7.snap
- .snapguidist/__snapshots__/TruncatedList-9.snap
- lib/auto-ui.js
- src/components/ui/TruncatedList.js
- src/components/ui/TruncatedList.md
- src/index.js
Requirement for https://github.com/x-team/auto/pull/1251
TruncatedList is an invisible component that receives a list of anything and creates truncation effect on it.
- **items** receives an array of anything: strings, numbers, elements, etc
- **visible** (optional) receives a number with the max amount of visible items
- **increment** (optional) receives a number with the amount of items to show on each step
- **viewMore** (optional) receives a callback that returns the view more clickable element
- **inserted** (optional) receives boolean, if truthy the view more button will appear on last item place if have 2 or more items to show on next step
> Include TruncatedList component

- .snapguidist/__snapshots__/Dropdown-3.snap
- lib/auto-ui.js
- src/components/ui/Dropdown.md
- src/components/ui/SelectBox.js
> Include lined prop on SelectBox for theming purposes

- lib/auto-ui.js
- src/components/ui/SelectBox.js
SelectBox changed to simpler version for redux usage.
Removed functions as we use redux actions for all api things and present code is not working with redux
> Create new list

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/Note-1.snap
- .snapguidist/__snapshots__/Note-3.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
> Fix white-space non wrapping bug on ApplicantBadge

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/Dropdown.js
- src/components/ui/TruncatedList.js
>  Make ApplicantBadge to be entirely clickable

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/ApplicantBadge.md
- Use CSS only for displaying/hiding dropdown icons
- Separate render logic for displaying dropdown menus
> Display controls on hover

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/ApplicantScreen-3.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/ApplicantBadge.md
Fixes x-team/auto#1294
- Adds on click callbacks for applicant badge actions.
- Navigate to the `ApplicantBadge` component section.
- Make sure the component passes regression.
branch | PR
`1294-exclude-registered-from-list--release-aug-6-12` | [Auto](https://github.com/x-team/auto/pull/1447)
`1294-exclude-registered-from-list--release-aug-6-12` | [Auto API](https://github.com/x-team/auto-api/pull/466)
> Add on click callbacks for applicant badge actions

- .snapguidist/__snapshots__/Dropdown-3.snap
- .snapguidist/__snapshots__/Dropdown-7.snap
- .snapguidist/__snapshots__/ListsEditor-1.snap
- .snapguidist/__snapshots__/Modal-5.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SelectBox-0.snap
- .snapguidist/__snapshots__/SelectBox-1.snap
- .snapguidist/__snapshots__/SelectBox-3.snap
- .snapguidist/__snapshots__/SelectBox-5.snap
- .snapguidist/__snapshots__/SelectBox-7.snap
- .snapguidist/__snapshots__/SelectBox-9.snap
- lib/auto-ui.js
- src/components/ui/ListsEditor.js
- src/components/ui/SelectBox.js
- src/components/ui/SelectBox.md
> Include new status for SelectBox items

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/Dropdown-1.snap
- .snapguidist/__snapshots__/Dropdown-11.snap
- .snapguidist/__snapshots__/Dropdown-3.snap
- .snapguidist/__snapshots__/Dropdown-5.snap
- .snapguidist/__snapshots__/Dropdown-7.snap
- .snapguidist/__snapshots__/Dropdown-9.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SelectBox-1.snap
- .snapguidist/__snapshots__/SelectBox-13.snap
- .snapguidist/__snapshots__/SelectBox-3.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/Dropdown.js
Fixes x-team/auto#1432
- Adds the bypass class names for applicant badge actions.
- Navigate to the `ApplicantBadge` component section.
- Make sure the component passes regression.
- Navigate to the `Dropdown` component section.
- Make sure the component passes regression.
- Navigate to the `SelectBox` component section.
- Make sure the component passes regression.
branch | PR
`1432-fix-style-for-applicants-exclusion-list-dropdown` | [Auto](https://github.com/x-team/auto/pull/1467)
> Add bypass class names for applicant badge actions

- .snapguidist/__snapshots__/ApplicantBadge-0.snap
- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantGrid-0.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/ApplicantGrid-5.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/ApplicantBadge.md
- src/components/ui/ApplicantGrid.js
- src/components/ui/ApplicantGrid.md
Requirement for https://zube.io/x-team/xp-formerly-auto/c/2282
- http://localhost:6060/#!/ApplicantBadge/5
- http://localhost:6060/#!/ApplicantGrid/3
> Search module tabular view for ApplicantGrid and ApplicantBadge

- .snapguidist/__snapshots__/Dropdown-3.snap
- .snapguidist/__snapshots__/Dropdown-7.snap
- .snapguidist/__snapshots__/ListsEditor-1.snap
- .snapguidist/__snapshots__/ListsEditor-3.snap
- .snapguidist/__snapshots__/Modal-5.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SelectBox-0.snap
- .snapguidist/__snapshots__/SelectBox-1.snap
- .snapguidist/__snapshots__/SelectBox-11.snap
- .snapguidist/__snapshots__/SelectBox-13.snap
- .snapguidist/__snapshots__/SelectBox-3.snap
- .snapguidist/__snapshots__/SelectBox-5.snap
- .snapguidist/__snapshots__/SelectBox-7.snap
- .snapguidist/__snapshots__/SelectBox-9.snap
- lib/auto-ui.js
- src/components/ui/SelectBox.js
Resolves https://github.com/x-team/auto/issues/1485
> Update delete confirmation buttons

- .snapguidist/__snapshots__/ColorPalette-1.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- lib/auto-ui.js
- src/styles/theme.js
Fixes https://github.com/x-team/auto/issues/1394 and is a complimentary one for https://github.com/x-team/auto/pull/1487
> Update typo text

- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- .snapguidist/__snapshots__/SelectBox-7.snap
- lib/auto-ui.js
- src/components/ui/ListsEditor.js
- src/components/ui/SelectBox.js
- src/components/ui/SelectBox.md
> Include unarchiving and unarchived SelectBox item status

- .snapguidist/__snapshots__/SelectBox-0.snap
- .snapguidist/__snapshots__/SelectBox-9.snap
- lib/auto-ui.js
- src/components/ui/SelectBox.js
- src/components/ui/SelectBox.md
Resolves https://github.com/x-team/auto/issues/1493
| Release branch | This PR |
| - | - |
| ![before](https://user-images.githubusercontent.com/131859/44669739-235b4380-a9f7-11e8-820c-e4e5b21f68b2.png) | ![after](https://user-images.githubusercontent.com/131859/44669677-e7c07980-a9f6-11e8-8406-1a6c949d1e8a.png) |
> Update SelectBox specs and fix the new test case

- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- lib/auto-ui.js
- src/components/ui/SearchForm.js
Fixes https://github.com/x-team/auto/issues/1495 and relates to https://github.com/x-team/auto/pull/1497
>  Fix modal open

- .snapguidist/__snapshots__/CollapsibleSection-11.snap
- .snapguidist/__snapshots__/CollapsibleSection-13.snap
- .snapguidist/__snapshots__/CollapsibleSection-15.snap
- .snapguidist/__snapshots__/CollapsibleSection-17.snap
- .snapguidist/__snapshots__/CollapsibleSection-5.snap
- .snapguidist/__snapshots__/CollapsibleSection-9.snap
- .snapguidist/__snapshots__/Keywords-1.snap
- .snapguidist/__snapshots__/Keywords-3.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- lib/auto-ui.js
- src/components/ui/CollapsibleSection.js
- src/components/ui/CollapsibleSection.md
Fixes https://github.com/x-team/auto/issues/1479
Returns the initial value for the state manager based on a passed value.
> Auto expand the more details of availability display

- .snapguidist/__snapshots__/ApplicantGridHeader-1.snap
- lib/auto-ui.js
- src/components/ui/ApplicantGridHeader.js
- src/components/ui/ApplicantGridHeader.md
- src/index.js
- src/utils/helpers.js
**Release Type:** *New feature*
Fixes #[XP-2161](https://x-team-internal.atlassian.net/browse/XP-2161)
A new ApplicantGridHeader component used for the ApplicantGrid
List related PRs against other Auto repos if applicable:
branch | PR
xp-2220-support-sorting-through-the-api-url | [Auto API](https://github.com/x-team/auto-api/pull/489)
1491-create-applicantgrid-header-with-sorting-functiona | [Auto](https://github.com/x-team/auto/pull/1515)
> Add ApplicantGridHeader component

- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SelectBox-15.snap
- lib/auto-ui.js
- src/components/ui/SearchForm.js
- src/components/ui/SelectBox.js
**Release Type:** *Breaking change*
These changes add a control flag (shouldSortItems) for items in the select box component to control whether the items should be sorted or not.
> Add shouldSortItems flag prop to SelectBox component

- .snapguidist/__snapshots__/Keywords-1.snap
- .snapguidist/__snapshots__/Keywords-3.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/NotesFeed-1.snap
- .snapguidist/__snapshots__/PencilButton-0.snap
- .snapguidist/__snapshots__/PencilButton-1.snap
- .snapguidist/__snapshots__/PencilButton-10.snap
- .snapguidist/__snapshots__/PencilButton-11.snap
- .snapguidist/__snapshots__/PencilButton-12.snap
- .snapguidist/__snapshots__/PencilButton-13.snap
- .snapguidist/__snapshots__/PencilButton-15.snap
- .snapguidist/__snapshots__/PencilButton-17.snap
- .snapguidist/__snapshots__/PencilButton-19.snap
- .snapguidist/__snapshots__/PencilButton-2.snap
- .snapguidist/__snapshots__/PencilButton-3.snap
- .snapguidist/__snapshots__/PencilButton-4.snap
- .snapguidist/__snapshots__/PencilButton-5.snap
- .snapguidist/__snapshots__/PencilButton-6.snap
- .snapguidist/__snapshots__/PencilButton-7.snap
- .snapguidist/__snapshots__/PencilButton-8.snap
- .snapguidist/__snapshots__/PencilButton-9.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- lib/auto-ui.js
- src/components/ui/PencilButton.js
- src/components/ui/PencilButton.md
- src/index.js
Fixes [XP-2159](https://x-team-internal.atlassian.net/browse/XP-2159)
This is the button that we're gonna be using on the Applicant form. It's gonna be used with the new Edit notes feature.
List related PRs against other Auto repos if applicable:
branch | PR
xp-2159-allow-editing-fields-master | [Auto](https://github.com/x-team/auto/pull/1530)
> Pencil Button component

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/ColorPalette-1.snap
- .snapguidist/__snapshots__/Keywords-1.snap
- .snapguidist/__snapshots__/Keywords-3.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/ApplicantBadge.md
- src/components/ui/ApplicantGrid.md
- src/styles/theme.js
**Release Type:** *Breaking change*
These changes add a status indicator to the applicant badge component.
This status indicator is a circle that can have three colors depending on the status:
- Accepted:  green
- Excluded:  red
- Pending: yellow
Applicant Badge Component.
> Add status indicator to applicant badge component

- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- lib/auto-ui.js
- src/components/ui/InlineEditor.js
Fixes [XP-2237](https://x-team-internal.atlassian.net/browse/XP-2237)
Add the property `type` to the action buttons and disable the `Save` button if the prop isValid is set to `false`.
List related PRs against other Auto repos if applicable:
branch | PR
xp-2237-implement-validators-email-and-location | [Auto](https://github.com/x-team/auto/pull/1534)
1. Activate the editor mode of the Location field by clicking the pencil button.
2. Fill it with an invalid location.
3. The `Save` button should be disabled.
3. If you fill it with a valid location, the `Save` button should be enabled.
> Add type attribute to the buttons and check the prop 'isValid'

- .snapguidist/__snapshots__/Dropdown-3.snap
- .snapguidist/__snapshots__/Dropdown-7.snap
- .snapguidist/__snapshots__/ListsEditor-1.snap
- .snapguidist/__snapshots__/ListsEditor-3.snap
- .snapguidist/__snapshots__/Modal-5.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- .snapguidist/__snapshots__/SelectBox-1.snap
- .snapguidist/__snapshots__/SelectBox-11.snap
- .snapguidist/__snapshots__/SelectBox-13.snap
- .snapguidist/__snapshots__/SelectBox-3.snap
- .snapguidist/__snapshots__/SelectBox-5.snap
- .snapguidist/__snapshots__/SelectBox-7.snap
- .snapguidist/__snapshots__/SelectBox-9.snap
- lib/auto-ui.js
- src/components/hocs/withProps.js
- src/components/ui/Dropdown.js
- src/components/ui/SearchForm.js
- src/components/ui/SelectBox.js
**Release Type:** *Breaking change*
These changes add the clear click functionality to the lists select and fix a bug on its lists filter when searching for a specific list item.
Select Box and Search box components.
> Add clear click functionality and fix bug on lists filter

- .snapguidist/__snapshots__/Keywords-1.snap
- .snapguidist/__snapshots__/Keywords-3.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- lib/auto-ui.js
- src/components/ui/SearchForm.js
- src/components/ui/SelectBox.js
**Release Type:** *Bug fix*
Fixes the list selection when the clear button is clicked
> Fix on clear method on select box

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-11.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
**Release Type:** *Bug fix* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2344
Just a quick fix to prevent the status circle to squeeze when applicant name is too big.
> Fix applicant badge status circle

- package-lock.json
- package.json
> Make npm scripts cross platform

- .snapguidist/__snapshots__/ApplicantBadge-1.snap
- .snapguidist/__snapshots__/ApplicantBadge-11.snap
- .snapguidist/__snapshots__/ApplicantBadge-17.snap
- .snapguidist/__snapshots__/ApplicantBadge-3.snap
- .snapguidist/__snapshots__/ApplicantBadge-5.snap
- .snapguidist/__snapshots__/ApplicantBadge-7.snap
- .snapguidist/__snapshots__/ApplicantBadge-9.snap
- .snapguidist/__snapshots__/ApplicantGrid-1.snap
- .snapguidist/__snapshots__/ApplicantGrid-3.snap
- .snapguidist/__snapshots__/Note-3.snap
- .snapguidist/__snapshots__/Note-5.snap
- .snapguidist/__snapshots__/Note-9.snap
- .snapguidist/__snapshots__/SearchForm-1.snap
- .snapguidist/__snapshots__/SearchForm-3.snap
- .snapguidist/__snapshots__/SearchForm-5.snap
- lib/auto-ui.js
- src/components/ui/ApplicantBadge.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2411
- I decided to change the position of the tooltip, that way we fix this issue and we are doing a safe change. I tried to modify the `Dropdown` component but I realized that the ticket can be a `Breaking change` if we do this. I think this fix can avoid more lateral issues on the website.
*N/A*
1- Go to Admin Page
2- Click on Tabular view
3- Hover the texts in the column `Avail. Date`
4- You should be able to see the tooltip at the bottom of the text
- **Admin Page - Tabular view**
> Change tooltip position

- package-lock.json
- package.json
- webpack.config.js
This will allow `auto` to load source maps from `auto-ui`'s dependencies as well.
> Enable source maps loader

- .storybook/addons.js
- .storybook/config.js
- package-lock.json
- package.json
Fixes https://x-team-internal.atlassian.net/browse/XP-2523 and add support for dynamically editing component right inside Storybook runtime.
**NOTE:** In order to change any specific component, this component should be altered to support knobs. Given that, I suggest doing that incrementally when there's a particular need and when writing new components' stories.
> Add support for Knobs to dynamically edit components in runtime

- .gitignore
- .travis.yml
- package.json
Fixes https://x-team-internal.atlassian.net/browse/XP-2521 and deploys to GitHub Pages when committing to `master`.
> Export Storybook as a static app

- src/components/ui/Button.js
- src/components/ui/Button.stories.js
- src/components/ui/Dropdown.js
- src/components/ui/SvgIcon.js
- src/components/ui/SvgIcon.stories.js
- src/styles/theme.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2695
> Upgraded `Button` and `SvgIcon` component to add a new style to `addToList` and `status` buttons.
- Added new colors options: `gray` and `grayPink`.
- Added a new prop `smallRounded` to have the posibiity to add `border-radius` of `2px`.
- Updated `Buttons.stories.js`
- Added a new icon called `plusquare`
- Added the option to accept the `rest` of props into the component, that way, for example, we can set custom `styles`.
- Updated `SvgIcon.stories.js`
branch | PR
XP-2695-upgrade-ui-status-addtolist | [Auto](https://github.com/x-team/auto/pull/1763)
- `Button.js` component
- `SvgIcon.js` …
> Upgrade button and SvgIcon component to adapt new style on auto

- src/components/ui/RichTextEditor.js
**Release Type:** *Bug fix* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2720
As wrote in the ticket in JIRA I am not able to reproduce this error. I followed the suggestion left by Nick to fix the issue but can not confirm that this solves it. 
erates as expected!
Type in any rich text field and write content and break lines. If you will reach the end of the veritcal space of that field the scrollbar should no longer overflow the text put into the text field.
All RichText fields used in the app.
>  Add bottom padding for rich text editor

- src/components/ui/ActivityLog.js
- src/components/ui/ActivityLog.stories.js
- src/components/ui/ActivityLogsDisplay.js
- src/components/ui/ActivityLogsDisplay.stories.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10026/tab/release-report-all-issues**
- `Update grouping of List Accept/Exclude Activity logs items`
- https://github.com/x-team/auto-ui/pull/328
> "Release-19" version

- src/components/ui/SelectBox.js
- src/components/ui/SelectBox.stories.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2755
Fix some rendering issues with long strings.
branch | PR
`XP-2755-fix-ui-for-addtolist-and-status-dropdowns` | [Auto](https://github.com/x-team/auto/pull/1790)
1. Grab the latest from this branch
2. Run `npm start`
3. Check-out the new story "width variations" at "SelectBox" showcases (http://localhost:9001/?selectedKind=UI%20Components%2FSelectBox&selectedStory=width%20variations)
4. Check all the demos and other SelectBox's stories, they should not have any regression
- `SelectBox`
> Fix long string handling for SelectBox items

- src/components/ui/Note.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2783
>  Note is not rendering after saved the new value
1- Go to Notes component in Storybook
2- Try to edit the note
3- After saving the note, that should be updated with the latest data.
- Notes Component
> Updated presenter render in Note component when is updated

- src/components/ui/Note.js
- src/components/ui/RichTextEditor.js
- src/components/ui/RichTextEditor.stories.js
- src/utils/helpers.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10027/tab/release-report-all-issues**
- `Use ToastUIEditorViewer component for rendering the rich text content`
- https://github.com/x-team/auto-ui/pull/331
> "Release-21" version

- src/components/ui/Collapsible/Body.js
- src/components/ui/Collapsible/Collapsible.stories.js
- src/components/ui/Collapsible/Container.js
- src/components/ui/Collapsible/Header.js
- src/components/ui/Collapsible/index.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2795
> The component should hold none design, only the behaviour and minimal CSS for positioning and display
> Add component into Storybook and provide stories for common and edge cases
Go to Storybook: http://localhost:9001/?selectedKind=UI%20Components%2FCollapsible&selectedStory=basic%20usage&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel&background=%23fff
> Create generic Collapsible component

- src/components/ui/RichTextEditor.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2830
> As you can see here https://d.pr/free/i/njIxsA when we add code into the code block and click the "Editor" button, it is rendered behind our left column in List UI.
> 
> Secondly, if we click the arrowed icon to maximize the screen we can reach a point where the whole screen is replaced with the code and seems to be blocked, there's no obvious way to return to the ListUI / Toast UI.
1- Go to http://localhost:9001/?selectedKind=UI%20Components%2FRichTextEditor&selectedStory=basic%20usage&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel&background=%23fff
2- Confirm that the …
> Remove editor button for codeblock

- src/components/ui/RichTextEditor.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10031/tab/release-report-all-issues**
- `ToastUI: Add a new "Code Block" toolbar button`
- https://github.com/x-team/auto-ui/pull/342
- `Toast UI Code Block Editor is not rendered correctly and can block the screen`
- https://github.com/x-team/auto-ui/pull/349
> "Release-24" version

- src/components/ui/GenericTabs/Container.js
- src/components/ui/GenericTabs/GenericTabs.stories.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2861
Include showcase that expose a behaviour that update activeTab based on prop update
branch | PR
`XP-2861-refresh-tabs-when-going-back-on-page-history` | [Auto](https://github.com/x-team/auto/pull/1830)
1. run the applicantion
1. go to http://localhost:8000/admin/search/advanced
1. switch from `list` and `all applicants` tabs
1. use browser's history buttons back and forward
1. observe that the active tab updates accordingly
1. run `npm start`
1. go to http://localhost:9001/?selectedKind=UI%20Components%2FGenericTabs%2FDebug&selectedStory=update%20activeTab%20from%20defaultActiveKey%20prop
1. click on `switch tabs` and observe the behavior is correct (more info on Storybook Notes section) …
> Include showcase that expose a behaviour that update activeTab based on prop update

- src/components/forms/InputField.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2896
> Add clear button on date input for InputField component
branch | PR
XP-2896-clear-availabile-before-input| [XP](https://github.com/x-team/xp/pull/1834)
Go to http://localhost:9001/?selectedKind=Form%20Components%2FInputField&selectedStory=Use%20date%20field&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel&background=%23fff and confirm that you can clear the date input using the `x` icon.
InputField component
> Add clear button on date input for InputField component

- src/components/ui/Filters/Filter.js
- src/components/ui/Filters/Filters.stories.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10036/tab/release-report-all-issues**
- `Remove "expand/collapse" triangle on "List Members" and Rate field`
- https://github.com/x-team/xp-ui/pull/358
> "Version-1.27.0" release

- src/components/ui/MetaGroup.js
- src/components/ui/MetaGroup.stories.js
- src/index.js
**Release Type:** *Non-breaking feature*
Fixes https://x-team-internal.atlassian.net/browse/XP-2892
Create MetaGroup component and add some Storybooks stories to bullet proof the component.
1. run `npm start`
1. go to http://localhost:9001/?selectedKind=UI%20Components%2FMetaGroup
1. go to http://localhost:9001/?selectedKind=UI%20Components%2FMetaGroup%2FDebug&selectedStory=responsive%20demonstration%20lots%20elements for a more debuggable showcase (check Notes informations)
- `MetaGroup` component
> Create MetaGroup component

- src/components/ui/ApplicantBadge.js
- src/components/ui/ApplicantBadge.stories.js
- src/components/ui/ListExclusionFormPopup.js
- src/components/ui/ListExclusionFormPopup.stories.js
**Release Type:** *Breaking Changes*
Fixes https://x-team-internal.atlassian.net/browse/XP-2929
Removed DropDown from ApplicantBadge, refactored calculations to arrow and names.
branch | PR
`XP-2929-wire-up-the-tooltip-ui-component-with-redux-in-the-application` | [XP](https://github.com/x-team/xp/pull/1849)
1. Filter component ListExclusionFormPopup
2. Check if arrows are in place when clicking on different buttons, check if name changes in all Popups
- `ui/ListExclusionFormPopup.js`
> Wire up the tooltip UI component

- src/components/ui/ListExclusionFormPopup.js
- src/components/ui/ListExclusionFormPopup.stories.js
**Release Type:** *Breaking Changes* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2946
Created story to better test the ListExclusionFormPopup in a real use case, and fixed arrow positioning.
xp_ui | [XP](https://github.com/x-team/xp-ui/pull/375)
xp_ui | [XP](https://github.com/x-team/xp-ui/pull/374)
1. Search for ListExclusionFormPopup 
2. Test the different use cases 
- `ui/ListExclusionFormPopup.js`
> Fixed Arrow Positioning when button close to the top

- src/components/ui/TwoColumnsLayout.js
- src/components/ui/TwoColumnsLayout.stories.js
**Release Type:** *RELEASE_TYPE* 
Fixes https://x-team-internal.atlassian.net/browse/XP-2959
Added new prop `contentID` to set the attribute `ID` to the content column
branch | PR
fix-profile-video | [XP](https://github.com/x-team/xp/pull/1859)
- TwoColumnsLayout
> Add prop to add content id for content column

- flow-typed/npm/react-copy-to-clipboard_v5.x.x.js
- package.json
- src/components/ui/GenericCopyToClipboard/GenericCopyToClipboard.stories.js
- src/components/ui/GenericCopyToClipboard/Tooltip.js
- src/components/ui/GenericCopyToClipboard/index.js
- src/index.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10045/tab/release-report-all-issues**
- **Copy email address to clipboard on admin facing Profile**
- https://github.com/x-team/xp-ui/pull/383
> "Version-2.2.0" release

- src/components/ui/ErrorBox.js
- src/components/ui/SettingsImportScreen.js
- src/components/ui/SettingsImportScreen.stories.js
- src/components/ui/SettingsScreen.js
- src/index.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2991
Create new `SettingsImportScreen` UI component
branch | PR
`XP-2991-create-import-profiles-screen` | [XP](https://github.com/x-team/xp/pull/1874)
- run `npm start`
- go to http://localhost:9001/?selectedKind=UI%20Components%2FSettingsImportScreen
> Create SettingsImportScreen UI component

- src/components/ui/SearchForm.stories.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2988
> Update applicant statuses in storybook to keep the data updated.
1- Go to http://localhost:9001/?selectedKind=UI%20Components%2FSearchForm&selectedStory=card%20view%20mode&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel&background=%23fff
2- Confirm that the `status` dropdown has the news statuses:
- Waitlist
- Shortlisted
- Booked
- Booked (Available Soon)
- Runway
- Out
- In Review
> Update applicasts statuses in storybooks

- src/components/hocs/withAutosize.js
- src/components/ui/Button.js
- src/components/ui/ErrorBox.js
- src/components/ui/SettingsImportScreen.js
- src/components/ui/SettingsImportScreen.stories.js
- src/components/ui/SettingsScreen.js
- src/index.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10049/tab/release-report-all-issues**
- **Import profiles to List as Accepted via email addresses newline separated file**
- https://github.com/x-team/xp-ui/pull/389
> "Version-2.3.0" release

- src/components/ui/SearchForm.stories.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10050/tab/release-report-all-issues**
- **Status field data migration**
- https://github.com/x-team/xp-ui/pull/391
> "Version-2.4.0" release

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/Filters/Filter.js
- src/components/ui/Filters/Filters.stories.js
- src/components/ui/Filters/Group.js
- src/components/ui/Filters/Heading.js
- src/components/ui/Filters/Label.js
- src/components/ui/Filters/TabButton.js
- src/components/ui/Filters/TabHeads.js
- src/components/ui/TwoColumnsLayout.js
- src/components/ui/TwoColumnsLayout.stories.js
Fixes https://x-team-internal.atlassian.net/browse/XP-2845
This PR fixes some remaining issues with TwoColumnsLayout and Filters sizings.
1. run `npm start`
1. go to http://localhost:9001/?selectedKind=UI%20Components%2FTwoColumnsLayout%2FUse%20cases&selectedStory=composed%20in%20AdminScreen%20with%20Filters
1. resize the screen
1. observe that the sidebar width are proportional to the screen width with value `30vw`
1. observe how the sidebar adjusts to a maximum width of `385px`
1. observe how the sidebar adjusts to a minimum width of `285px`
- `Filters/Filter.js`
- `Filters/Filters.stories.js`
- `Filters/Group.js`
- `Filters/Heading.js`
- `Filters/Label.js`
- `Filters/TabButton.js`
- `Filters/TabHeads.js`
- `TwoColumnsLayout.js`
- …
> Fix sizing issues with TwoColumnsLayout and Filters

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/Filters/Filter.js
- src/components/ui/Filters/Filters.stories.js
- src/components/ui/Filters/Group.js
- src/components/ui/Filters/Heading.js
- src/components/ui/Filters/Label.js
- src/components/ui/Filters/TabButton.js
- src/components/ui/Filters/TabHeads.js
- src/components/ui/TwoColumnsLayout.js
- src/components/ui/TwoColumnsLayout.stories.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10053/tab/release-report-all-issues**
- **Correct TwoColumnsLayout sizing to make it fluid on smaller screens**
- https://github.com/x-team/xp-ui/pull/354
> "Version-2.6.0" release

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/ApplicantGrid.stories.js
- src/components/ui/Filters/Container.js
- src/components/ui/Filters/Filters.stories.js
- src/components/ui/Filters/Group.js
- src/components/ui/Filters/Heading.js
- src/components/ui/Filters/SubHeading.js
- src/components/ui/Filters/index.js
- src/components/ui/GenericCollapsible/Container.js
- src/components/ui/GenericCollapsible/GenericCollapsible.stories.js
Fixes https://x-team-internal.atlassian.net/browse/XP-3097
Add accordion effect on GenericCollapsible and Filters. Note that this is not breaking changes as the previous behaviour is still valid and remained the default.
branch | PR
`XP-3053-search-profile-display` | [XP](https://github.com/x-team/xp-ui/pull/404)
1. Check `GenericCollapsible` demonstration with accordion: http://localhost:9001/?selectedKind=UI%20Components%2FGenericCollapsible&selectedStory=basic%20usage%20with%20accordion%20effect
1. Check `Filters` demonstration with accordion: http://localhost:9001/?selectedKind=UI%20Components%2FFilters&selectedStory=example%20of%20complete%20composition%20with%20accordion%20effect
- GenericCollapsible
- Filters
> Add accordion effect on GenericCollapsible and Filters

- src/components/ui/SearchResult.js
**Release Type:** *Non-Breaking changes* 
Fixes https://x-team-internal.atlassian.net/browse/XP-3146
Make vertical spacing around meta details row above search grid equal.
Compare Search header from previous version to this one.
Search panel header spacing.
> Remove extra top padding

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/Filters/Filter.js
- src/components/ui/Filters/Filters.stories.js
- src/components/ui/Filters/Group.js
- src/components/ui/Filters/Heading.js
- src/components/ui/Filters/Label.js
- src/components/ui/Filters/SubHeading.js
- src/components/ui/Filters/TabHeads.js
- src/components/ui/GenericCollapsible/Body.js
Fixes https://x-team-internal.atlassian.net/browse/XP-3150
Ensure Search sidebar matches designs.
branch | PR
`XP-3150-ensure-search-sidebar-matches-designs` | [XP](https://github.com/x-team/xp/pull/1948)
- Check the showcase http://localhost:9001/?selectedKind=UI%20Components%2FFilters%2FDebug&selectedStory=centered%20Filter%20Groups
Filters component.
> Ensure Search sidebar matches designs

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/Filters/Counter.js
- src/components/ui/Filters/Filters.stories.js
- src/components/ui/Filters/index.js
- src/styles/theme.js
Fixes https://x-team-internal.atlassian.net/browse/XP-3099
Counter component (simple label with coloring) to be used inside Filter headings.
branch | PR
XP-3099-add-counters-for-filters-and-results | [XP](https://github.com/x-team/xp/pull/1945)
Please refer to screenshot.
Filters component.
> Add Counter component to Filters

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/Filters/Counter.js
- src/components/ui/Filters/Filter.js
- src/components/ui/Filters/Filters.stories.js
- src/components/ui/Filters/Group.js
- src/components/ui/Filters/Heading.js
- src/components/ui/Filters/Label.js
- src/components/ui/Filters/SubHeading.js
- src/components/ui/Filters/TabHeads.js
- src/components/ui/Filters/index.js
- src/components/ui/GenericCollapsible/Body.js
- src/styles/theme.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10066/tab/release-report-all-issues**
- **Add counter for filters and results**
- https://github.com/x-team/xp-ui/pull/413
- **Ensure search sidebar matches designs**
- https://github.com/x-team/xp-ui/pull/414
> "Version-3.1.0" release

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/DataGrid.js
Fixes https://x-team-internal.atlassian.net/browse/XP-3160
Decrease size reduction for DataGrid.
- Open the app in a resolution of 768 height
- Resize the viewport screen vertically and observe that the DataGrid adjusts to the available space
DataGrid
> Increase Search Grid size

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/DataGrid.js
- src/components/ui/DataGrid.stories.js
Fixes https://x-team-internal.atlassian.net/browse/XP-3041
Change the visual of the loading state of DataGrid
branch | PR
`XP-3041-change-the-way-we-render-data-grid-and-loading-spinner-on-changing-data` | [XP](https://github.com/x-team/xp/pull/1959)
- check the story http://localhost:9001/?selectedKind=UI%20Components%2FDataGrid&selectedStory=loading
DataGrid component
> Change the DataGrid loading state

- src/__snapshots__/storyshots.test.js.snap
- src/components/ui/DataGrid.js
- src/components/ui/DataGrid.stories.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10068/tab/release-report-all-issues**
- **Increase Search Grid size**
- https://github.com/x-team/xp-ui/pull/416
**Change the way we render data-grid and loading spinner on changing data**
- https://github.com/x-team/xp-ui/pull/417
> "Version-3.2.0" release

- src/__snapshots__/storyshots.test.js.snap
- src/components/forms/SolutionForm/index.js
- src/components/ui/ApplicantBadge.js
- src/components/ui/ApplicantGrid.js
- src/components/ui/Button.js
- src/components/ui/DataGrid.js
- src/components/ui/Dropdown.js
- src/components/ui/Filters/Filter.js
- src/components/ui/Filters/Group.js
- src/components/ui/Filters/Heading.js
- src/components/ui/Filters/Label.js
- src/components/ui/Filters/TabButton.js
- src/components/ui/HeadingWithQuickSearch.js
- src/components/ui/ListExclusionFormPopup.js
- src/components/ui/ListsEditor.js
- src/components/ui/MetaGroup.js
- src/components/ui/QuickSearchButton.js
- src/components/ui/RoadmapLevel.js
- src/components/ui/SearchResult.js
**Release Notes: https://x-team-internal.atlassian.net/projects/XP/versions/10070/tab/release-report-all-issues**
- **Search features by user interaction cases**
- https://github.com/x-team/xp-ui/pull/425
- **Advanced search grid vertical scrolling allows for scrolling even when there are no items to show**
- https://github.com/x-team/xp-ui/pull/420
> "Version-3.4.0" release

- src/utils/constants.js
- src/utils/types.js
Fixes https://x-team-internal.atlassian.net/browse/XP-3220
Remove unused code related to old search
- No regressions or errors should be seen during build and/or in the app
> Remove code related to old search

- src/components/ui/ApplicantScreenNotification.js
- src/components/ui/EmptyState.js
- src/components/ui/HeaderBar.js
- src/components/ui/JobApplicationCard.js
- src/components/ui/JobCard.js
- src/components/ui/JobDetails.js
- src/components/ui/Modal.js
- src/components/ui/WelcomeHero.js
**Release Type:** *Dev Improvement* 
Fixes https://x-team-internal.atlassian.net/browse/XP-3689
**This PR supersedes https://github.com/x-team/xp-ui/pull/524, which has been closed due to rebase issues**
- Cypress best practices require the use of the data-testid attribute, rather than className or id
- The components required to run the View Jobs Board E2E have had the `data-testid` attribute added to them in accordance with previously established naming conventions.
- The affected components are listed below in "Impacted areas of application"
**Before submitting a Pull Request,** please make sure the following is done:
branch | PR
xp_branch_name | [XP](https://github.com/x-team/xp/pull/X)
XP-3689-Add-data-testid-to-job-related-components | [XP …
> Add `data-testid` attribute to job related components

- package-lock.json
- src/components/ui/CustomSelector.js
- src/components/ui/Timeframe.js
- src/components/ui/WorkExperience/WorkExperienceEntryPresenter.js
- src/components/ui/WorkExperience/WorkExperienceEntryPresenter.stories.js
- src/components/ui/WorkExperience/index.js
- src/components/ui/WorkExperience/index.stories.js
**Release Type:** *UI Improvement*
Part of https://x-team-internal.atlassian.net/browse/XP-3737
Made a number of style improvements to make the WorkExperience components integrate better into the XP Admin stylesheet.
- remove typographical styles so that text inherits its styles from the container
- move the pencil icon which switches to edit mode onto the right side of the header (requires changes to `WorkExperiencePresenter`)
- change header styles to match other headers used in XP
- remove unnecessary bottom borders
- minor tweaks to margins around several elements
branch | PR
XP-3401-admin-work-experience | [XP](https://github.com/x-team/xp/pull/2072)
View the steps on the XP pull request above to integrate into XP and view the styles in their intended context.
XP …
> Admin work experience styles
